In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import plotly.graph_objs as go
import yfinance as yf

%matplotlib inline
#import sklearn

/Users/rajgouravj/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [3]:
import pandas_datareader as pdr


import pyalgotrade
import talib

In [4]:
# Define the instruments to download. We would like to see Apple, Microsoft and the S&P500 index.
tickers = ['AAPL', 'MSFT', '^GSPC']

# We would like all available data from 01/01/2000 until 12/31/2016.
start_date = '2010-01-01'
end_date = '2016-12-31'

# User pandas_reader.data.DataReader to load the desired data. As simple as that.
panel_y_data = pdr.DataReader('INPX', 'yahoo', start_date, end_date)
#panel_g_data = pdr.data.DataReader('INPX', 'yahoo', start_date, end_date)

In [5]:
panel_y_data

                High       Low      Open     Close  Volume  Adj Close
Date
2012-08-03  680400.0  680400.0  680400.0  680400.0     0.0   680400.0
2012-08-06  680400.0  680400.0  680400.0  680400.0     0.0   680400.0
2012-08-07  243000.0  243000.0  243000.0  243000.0     0.0   243000.0
2012-08-08  243000.0  243000.0  243000.0  243000.0     0.0   243000.0
2012-08-09  729000.0  729000.0  729000.0  729000.0     0.0   729000.0
...              ...       ...       ...       ...     ...        ...
2016-12-23  221130.0  182250.0  221130.0  187920.0     1.0   187920.0
2016-12-27  225180.0  194400.0  197640.0  217890.0     1.0   217890.0
2016-12-28  233280.0  210600.0  226800.0  214650.0     1.0   214650.0
2016-12-29  259200.0  214650.0  226800.0  225990.0     3.0   225990.0
2016-12-30  222750.0  190350.0  212220.0  197640.0     1.0   197640.0

[1110 rows x 6 columns]